server:
  port:5005

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_user_db
    username: root
    password: Mad20041
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
