server:
  port: 5008

spring:
  application:
    name: Flight_ops_Service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_FlightOpsService_db
    username: root
    password: Mad20041

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



