server:
  port: 5009

spring:
  application:
    name: Seat_service

  datasource:
    url: jdbc:mysql://localhost:3306/airline_SeatService_db
    username: root
    password: Mad20041

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true